permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Compendial"
  description: |
    A global, subscription box resource for skincare. We bring you the best the planet has to offer, one box— one country— at a time.
  font_url: "https://fonts.googleapis.com/css?family=Roboto:400,700"

  colors:
    background: "--color-background"
    sidebar: "--color-banners"
    accent: "--color-accent"
    patterns:
      brand.logo: "--color-primary"
      cards.icon-card: "--color-banners"
      cards.product-card: "--color-banners"
      cards.product-details-card: "--color-banners"
      cards.image-card: "--color-banners"
      cards.checkout-card: "--color-banners"
      cards.total: "--color-banners"

  rationales:
    typefaces.primary: |
      Georgia was selected as the primary typeface for this site for its friendly typographic personality, and readability at a variety of sizes. It is also ideal for optimized loading times, and as such, appears in most content in the site.
    typefaces.secondary: |
      Roboto was selected as the secondary typeface to juxtapose Georgia. As a sans-serif font, it is ideal for creating contrasting headers. Monowidth in design, it is also extremely readable at a variety of sizes.
    colors.primary: |
      This primary colors were chosen to for their extreme readability on the given backgrounds. As such, they are the basis for all segments of text content, and serve as the hover states in most instances for page elements.
    colors.accent: |
      These colors serve different functions.


      Greyed text allows enough value contrast to be readable against the background, but does not distract from more important information on the page. It is ideal for, amongst other things, form placeholders.


      Accent is used to draw attention to the most important calls-to-action on a page, and as such, is only found in particular button instances, and to highlight links.


      Banners is used in headers and footers to create some subtle aesthetic variation on the page, and more generally appeals to the target demographic of the site. It is still light enough to maintain readability of text.


      Background serves as a base colour for the page. It is also employed in hover states for maximal value contrast.


      Alarm is the colour used to indicate page errors, such as incomplete form fields.

  layouts:
    default: |
      The default layout contains the standard header and footer for the website, as well as the general metadata, links, and scripts required to run the site.
    product: |
      The product layout contains the default layout's content, as well as the basis for product promotion content.

collections:
  products:
    output: true

defaults:
  - scope:
      path: _products
    values:
      layout: product
