title: "Footer"
description: |
  This is a list of all the styles for the footer of the website.

patterns:
  footer:
    title: "Site Footer"
    description: |
      This is the footer of the website.
