title: "Buttons"
description: |
  This is a list of all the styles of buttons that appear on the website.

patterns:
  accent:
    title: "Accent Button"
    description: |
      This button is used on white backgrounds, and serves to draw attention to the most important call-to-action on a page.
    width: 10em
    fields:
      - name: text
        type: string
        example: "Start now!"
      - name: url
        type: url
        example: "#"
      - name: aria
        type: string
        example: "This button links to the Products page"
  basic:
    title: "Basic Button"
    description: |
      This button is used on white backgrounds, and occassionally on website banners. It is the default button styling.
    width: 10em
    fields:
      - name: text
        type: string
        example: "Shop now"
      - name: url
        type: url
        example: "#"
      - name: aria
        type: string
        example: "This button links to the Products page"
  contact-submit:
    title: "Submitting Contact Form Button"
    description: |
      This button style is used to submit the contact form, found in the footer.
    fields:
      - name: text
        type: string
        example: "Stay in Touch"
      - name: aria
        type: string
        example: "This button submits your email, so we can stay in touch via newsletter"
  edit:
    title: "Edit Selection Button"
    description: |
      This button style is used to edit product selections in a user's cart.
    fields:
      - name: text
        type: string
        example: "Edit Selection"
      - name: url
        type: url
        example: "#"
      - name: aria
        type: string
        example: "This button will take you to the Product page"
  footer-links:
    title: "Footer Links"
    description: |
      These text links are used in the footer to link to other pages on the site that are of a lower priority than those found in the header.
    fields:
      - name: url
        type: url
        example: "#"
      - name: aria
        type: string
        example: "This button navigates you to our FAQ page"
      - name: id
        type: string
        example: "faq"
      - name: text
        type: string
        example: "FAQ"
  header:
    title: "Header Button"
    description: |
      This button style is used for page navigation in the header at larger screen sizes.
    fields:
      - name: text
        type: string
        example: "About Us"
      - name: url
        type: url
        example: "#"
      - name: aria
        type: string
        example: "This button will take you to the About Us page"
  search:
    title: "Sitewide Search Submit Button"
    description: |
      This button style is used to submit the sitewide search form, found in the header.
    fields:
      - name: aria
        type: string
        example: "This button will submit your search"
      - name: id
        type: string
        example: "search"
  social-icons:
    title: "Social Icons"
    description: |
      These buttons are used to link to existing social media profiles in the footer of the website.
    fields:
      - name: url
        type: url
        example: "#"
      - name: aria
        type: string
        example: "This button navigates you to our Facebook page"
      - name: id
        type: string
        example: "facebook"
  submit:
    title: "Submitting Forms Button"
    description: |
      This button style is used to submit forms, like the checkout page. It looks identical to the accent button, but is built differently.
    width: 15em
    fields:
      - name: text
        type: string
        example: "Confirm & Pay"
      - name: aria
        type: string
        example: "This button will submit your shipping and payment information"
  transparent:
    title: "Transparent Button"
    description: |
      This button style is used for banner cards on top of photos. It should be used sparingly, given how finicky it is.
    width: 10em
    fields:
      - name: text
        type: string
        example: "Shop now!"
      - name: url
        type: url
        example: "#"
      - name: aria
        type: string
        example: "This button will take you to the Products page"
