title: "Header"
description: |
  This is a list of all the styles for the header of the website.

patterns:
  header:
    title: "Site Header"
    description: |
      This is the main header of the website. Ideally, it would have incorporated JavaSript and not have been built so shoddily, but here we are.
