title: "Cards"
description: |
  This is a list of all the styles of cards used on this website.

patterns:
  icon-card:
    title: "Icon Card"
    description: |
      This is an example of an icon card; these are found on the landing page, and primarily function to help describe this service to potential customers. They do not link to anything.
    fields:
      - name: id
        type: string
        example: "how-it-works"
      - name: header
        type: string
        example: "How it works"
      - name: aria
        type: string
        example: "This is information about how purchases through our website work."
      - name: text
        type: string
        example: "You want to try and improve your skincare routine. We want to help. With our service, you’ll receive the best the world has to offer in terms of skincare every month, shippedright to your home. It’s that easy."
  product-card:
    title: "Product Card"
    description: |
      This button is used on white backgrounds, and serves to draw attention to the most important call-to-action on a page.
    fields:
      - name: text
        type: string
        example: "Start now!"
      - name: url
        type: string
        example: "#"
      - name: aria
        type: string
        example: "This button links to the Products page"
