title: "Cards"
description: |
  This is a list of all the styles of cards used on this website.

patterns:
  icon-card:
    title: "Icon Card"
    description: |
      This is an example of an icon card; these are found on the landing page, and primarily function to help describe this service to potential customers. They do not link to anything.
    fields:
      - name: id
        type: string
        example: "how-it-works"
      - name: header
        type: string
        example: "How it works"
      - name: aria
        type: string
        example: "This is information about how purchases through our website work."
      - name: text
        type: string
        example: "You want to try and improve your skincare routine. We want to help. With our service, you’ll receive the best the world has to offer in terms of skincare every month, shipped right to your home. It’s that easy."
  product-card:
    title: "Product Card"
    description: |
      This card is used to list products in an organized fashion on the product page.
    width: 20em
    fields:
      - name: data
        type: object
        data:
          source: "site.products[0]"
  product-details-card:
    title: "Product Details Card"
    description: |
      This card is used to display a product's details to a user.
    width: 25em
    fields:
      - name: method
        type: string
        example: "POST"
      - name: data
        type: object
        data:
          source: "site.products[0]"
  image-card:
    title: "Alternating Image Cards"
    description: |
      This card is used to further advertise products on the homepage, but only appears at larger screen sizes.
    fields:
      - name: header
        type: string
        example: "This month: Japan"
      - name: text
        type: string
        example: "This month features a variety of products that hail from the land of the rising sun. Cleansing oils, overnight creams, masks, and essences, this box has everything you need and more."
      - name: image-file
        type: string
        example: "caffeine.jpg"
      - name: header-two
        type: string
        example: "Next month: Seychelles"
      - name: text-two
        type: string
        example: "Next month, we'll help you to escape to the tropics. Bring lasting hydration and new-found firmness to your skin with this Vitamin C care package, crafted in paradise."
      - name: image-file-two
        type: string
        example: "grapefruit-box.jpg"
  checkout-card:
    title: "Checkout Card"
    description: |
      This card is used to list products a user has placed into their cart for purchase.
    fields:
      - name: aria
        type: string
        example: "This is a product card, featuring this month's product offerings"
      - name: image-file
        type: string
        example: "caffeine.jpg"
      - name: header
        type: string
        example: "This month: Japan"
      - name: cost
        type: float
        example: 55.00
      - name: text
        type: string
        example: "This month features a variety of products that hail from the land of the rising sun. Cleansing oils, overnight creams, masks, and essences, this box has everything you need and more."
      - name: option
        type: string
        example: "Avocado-free"
      - name: quantity
        type: integer
        example: 1
  total:
    title: "Purchase Total Calculation Card"
    description: |
      This card is used to summarize the user's purchase, and all associated costs and discounts. It is always paired with the Checkout Card.
    fields:
      - name: caption
        type: string
        example: "Order Summary"
      - name: header1
        type: string
        example: "Subtotal"
      - name: cell1
        type: float
        example: 110.00
      - name: header2
        type: string
        example: "Shipping"
      - name: cell2
        type: float
        example: 0
      - name: header3
        type: string
        example: "Taxes"
      - name: cell3
        type: float
        example: 11.00
      - name: header4
        type: string
        example: "Discounts"
      - name: cell4
        type: float
        example: 0
      - name: header5
        type: string
        example: "Total"
      - name: cell5
        type: float
        example: 121.00
  banner-card:
    title: "Banner Card"
    description: |
      This card is used only in headers that incorporate a photographic background.
    fields:
      - name: h1
        type: string
        example: "Discover a whole world of options"
