title: "Cards"
description: |
  This is a list of all the styles of cards used on this website.

patterns:
  icon-card:
    title: "Icon Card"
    description: |
      This is an example of an icon card; these are found on the landing page, and primarily function to help describe this service to potential customers. They do not link to anything.
    fields:
      - name: id
        type: string
        example: "how-it-works"
      - name: header
        type: string
        example: "How it works"
      - name: aria
        type: string
        example: "This is information about how purchases through our website work."
      - name: text
        type: string
        example: "You want to try and improve your skincare routine. We want to help. With our service, you’ll receive the best the world has to offer in terms of skincare every month, shippedright to your home. It’s that easy."
  product-card:
    title: "Product Card"
    description: |
      This card is used to list products in an organized fashion on the product page.
    fields:
      - name: aria
        type: string
        example: "This is a product card, featuring this month's product offerings"
      - name: image-file
        type: string
        example: "caffeine.jpg"
      - name: alt-text
        type: string
        example: "This is a photo of the Japan subscription box, featuring caffeined eye drops"
      - name: header
        type: string
        example: "This month: Japan"
      - name: cost
        type: string
        example: "$55.00"
      - name: text
        type: string
        example: "This month features a variety of products that hail from the land of the rising sun. Cleansing oils, overnight creams, masks, and essences, this box has everything you need and more."
  image-card:
    title: "Alternating Image Cards"
    description: |
      This card is used to further advertise products on the homepage, but only appears at larger screen sizes.
    fields:
      - name: aria
        type: string
        example: "This is an image card, featuring products and sales on the homepage"
      - name: header
        type: string
        example: "This month: Japan"
      - name: text
        type: string
        example: "This month features a variety of products that hail from the land of the rising sun. Cleansing oils, overnight creams, masks, and essences, this box has everything you need and more. "
      - name: image-file
        type: string
        example: "caffeine.jpg"
      - name: alt-text
        type: string
        example: "This is a photo of the Japan subscription box, featuring caffeined eye drops"
